<?php
require('./fpdf186/fpdf.php');

// Create PDF
$pdf = new FPDF('P', 'mm', "A4");
$pdf->AddPage();
$pdf->SetFont('Arial', 'BUI', 20);

// Title
$pageWidth = $pdf->GetPageWidth();
$titleText = "Logo here";
$titleWidth = $pdf->GetStringWidth($titleText);
$xTitle = ($pageWidth - $titleWidth) / 2;

$pdf->SetX($xTitle);
$pdf->Cell($titleWidth, 10, $titleText, 0, 1, 'C');

$title = "QUOTATION";
// $titleWidth = $pdf->GetStringWidth($title);
// $xTitle = ($pageWidth - $titleWidth) / 2;


$pdf->SetFillColor(0,0,128);
$pdf->SetFont('Times', 'B', 25);
$pdf->SetTextColor(255,255,255);
// $pdf->SetX($xTitle);
$pdf->Cell(190, 15, $title, 0, 1, 'C',true);



$pdf->SetTextColor(0,0,0);
// Customer Details
$pdf->SetY(40);
$pdf->SetFont('Times', '', 15);
$pdf->Cell(50, 5, "Quote No:", 0, 1);
$pdf->SetFont('Times', '', 15);
$date = date('F j, Y');
$pdf->SetFont('Times', 'B', 15);
$pdf->Cell(40, 7, "Customer Name:", 1, 0);
$pdf->SetFont('Times', '', 15);
$pdf->Cell(0, 7, "Name", 1, 0);
$pdf->Cell(0, 7, "Date: $date", 0, 1, 'R');
$pdf->SetFont('Times', 'B', 15);
$pdf->Cell(40, 7, "Address:", 1, 0);
$pdf->SetFont('Times', '', 15);
$pdf->Cell(0, 7, "Erandwane,", 1, 1);
$pdf->SetFont('Times', 'B', 15);
$pdf->Cell(40, 7, "Mobile-1:", 1, 0);
$pdf->SetFont('Times', '', 15);
$pdf->Cell(80, 7, "0000000000", 1, 0);
$pdf->SetFont('Times', 'B', 15);
$pdf->Cell(30, 7, "Mobile-2:", 1, 0);
$pdf->SetFont('Times', '', 15);
$pdf->Cell(0, 7, "0000000000", 1, 1);
$pdf->SetFont('Times', 'B', 15);
$pdf->Cell(60, 7, "Contact Person Name:", 1, 0);
$pdf->SetFont('Times', '', 15);
$pdf->Cell(0, 7, "Name", 1, 1);
$pdf->SetFont('Times', 'B', 15);
$pdf->Cell(40, 7, "Email:", 1, 0);
$pdf->SetFont('Times', '', 15);
$pdf->Cell(0, 7, "email@gmail.com", 1, 0);

// Table Header
$pdf->SetY(90);
$pdf->SetFont('Times', 'B', 15);
$pdf->Cell(0, 7, 'WEBSITE PACKAGE', 1, 1, 'C', false);


// Table Content
$pdf->SetFont('Arial', '', 10);
$pdf->MultiCell(0, 7,"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio minima odit, dignissimos voluptatem explicabo, magnam placeat quos rem error repellat ut veniam enim totam sunt doloribus eaque recusandae. Dolore fugit dolores, deleniti perferendis cupiditate ut numquam itaque quam minima. Temporibus fugit ipsum deleniti recusandae aliquam? Placeat ut excepturi explicabo quo eligendi quas commodi maxime expedita. Perspiciatis voluptatum sint, reprehenderit molestias consequuntur quaerat magni, praesentium, dolorum commodi incidunt natus dolore molestiae laudantium blanditiis maiores accusamus repellendus veritatis? Ipsa, eos. Eveniet, eligendi possimus. Recusandae quam modi id facere corrupti illo deserunt tempora, assumenda expedita cum, dolorum nobis quaerat, voluptatem sit dignissimos eos!", 1);


$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(30,7,"MRP:",1,0);
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(100,7,"9999 /-",1,0);

$pdf->SetFont('Times', 'B', 10);
$pdf->Cell(30,7,"Offer Price:",1,0);
$pdf->SetFont('Times', 'B', 12);
$pdf->Cell(0,7,"9999 /-",1,1);

$pdf->SetFont('Times','B',10);
$pdf->MultiCell(0,7,"Terms and conditions",1,'C',false);

// Taxes and Total
// $tax = number_format(0 * $offerprice, 2); // 18% tax
// $finalamt = number_format($offerprice + $tax, 2);

$pdf->SetY(-62);
$pdf->SetFont('Times','B',15);
$pdf->Cell(0,15,"FOR WEBMIRCHI IT SOLUTIONS",0,1,'R');

$pdf->SetY(-50);
$pdf->SetFont('Times','',10);
$pdf->Cell(0,5,"  Webmirchi IT Solutions, Sr.No.43/14, Prasad Apartment, Ground Floor, Near Bank of India, Erandwane, Pune, Maharashtra 411004  ",'LTR',1,'C');
$pdf->Cell(0,5,"Mobile No: 9850639994, 9325229999",'LR',1,'C');
$pdf->Cell(0,5,"Email ID: info@webmirchi.com, Website: www.webmirchi.com",'LRB',1,'C');

// Footer
$pdf->SetFont('Arial', 'I', 8);
$pdf->SetY(-35);
$pdf->Cell(0, 10, 'quotation generated by Webmirchi Pvt. Ltd.', 0, 1, 'C');

// Output the PDF
ob_end_clean(); // Clear the buffer
$pdf->Output('I', 'Quotation.pdf'); // Display in the browser
exit; // Stop further script execution

?>